name: Deploy VuePress
on:
  push:
    branches: [ vue-playground ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2.3.3
        with:
          token: ${{ secrets.ASGARDEO_DOCS_GITHUB_BOT_TOKEN }}
      - name: Build and Deploy to Github Pages
        uses: jenkey2011/vuepress-deploy@v1.6.1
        env:
          ACCESS_TOKEN: ${{ secrets.ASGARDEO_DOCS_GITHUB_BOT_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist
