name: PR builder

on:
  pull_request:
    branches: [ vue-playground ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2.3.3
        with:
          ref: vue-playground
          token: ${{ secrets.ASGARDEO_DOCS_GITHUB_BOT_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
