name: Release Docs
on:
  push:
    branches: [ main ]
    paths-ignore:
      - package.json

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2.3.3
        with:
          token: ${{ secrets.ASGARDEO_DOCS_GITHUB_BOT_TOKEN }}
      - name: Build and Release version
        env:
          ACCESS_TOKEN: ${{ secrets.ASGARDEO_DOCS_GITHUB_BOT_TOKEN }}
        run: bash asgardeo-docs-builder.sh $GITHUB_WORKSPACE $ACCESS_TOKEN
